/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fees_management;

import com.mycompany.fees_management.model.databaseHelper;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ASUS
 */
public class Print_reciept extends javax.swing.JFrame {

	/**
	 * Creates new form Print_reciept
	 */
	public Print_reciept() {
		initComponents();
                setLocationRelativeTo(null);
		display_TT_print();
	}

	public void display_TT_print() {
		String sql = "SELECT TOP 1 * FROM fess_details ORDER BY reciept_no DESC;";
		try {
			Connection con = databaseHelper.openConnection();
			PreparedStatement pstmt = con.prepareStatement(sql);
			ResultSet rs = pstmt.executeQuery();
			rs.next();
			txt_reclept.setText(rs.getString("reciept_no"));
			txt_payment_mode.setText(rs.getString("payment_mode"));
			txt_ddno.setText(rs.getString("dd_no"));
			txt_cheque_no.setText(rs.getString("cheque_no"));
			txt_bank_name.setText(rs.getString("bank_name"));
			txt_student_name.setText(rs.getString("student_name"));
			txt_year1.setText(rs.getString("year1"));
			txt_year2.setText(rs.getString("year2"));
			txt_course.setText(rs.getString("course_name"));
			txt_roll_no.setText(rs.getString("roll_no"));
			txt_date.setText(rs.getString("date"));
			txt_amount.setText(rs.getString("amount"));
			txt_cgst.setText(rs.getString("cgst"));
			txt_sgst.setText(rs.getString("sgst"));
			txt_GSTIN.setText(rs.getString("gstin"));
			txt_total_amount.setText(rs.getString("total_amount"));
			txt_total_in_words.setText(rs.getString("totals_in_words"));
			txt_remark.setText(rs.getString("remark"));

		} catch (Exception e) {
			e.printStackTrace();
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_search_record = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_edit = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_course_list = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_view_all_record = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_back = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_print = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        table_print = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txt_GSTIN = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jlb_bankname = new javax.swing.JLabel();
        jlb_cheque_no = new javax.swing.JLabel();
        jlb_ddo = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_payment_mode = new javax.swing.JLabel();
        txt_cheque_no = new javax.swing.JLabel();
        txt_ddno = new javax.swing.JLabel();
        txt_bank_name = new javax.swing.JLabel();
        txt_reclept = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        txt_student_name = new javax.swing.JLabel();
        txt_course = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        txt_reclept9 = new javax.swing.JLabel();
        txt_roll_no = new javax.swing.JLabel();
        txt_total_amount = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        txt_amount = new javax.swing.JLabel();
        txt_remark = new javax.swing.JLabel();
        txt_sgst = new javax.swing.JLabel();
        txt_total_in_words = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        btn_home.setBackground(new java.awt.Color(0, 102, 102));
        btn_home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
        });
        btn_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        jLabel2.setText("  Home");
        btn_home.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 190, 70));

        btn_search_record.setBackground(new java.awt.Color(0, 102, 102));
        btn_search_record.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btn_search_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_search_recordMouseClicked(evt);
            }
        });
        btn_search_record.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search2.png"))); // NOI18N
        jLabel3.setText("Search Record");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        btn_search_record.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 200, 70));

        btn_edit.setBackground(new java.awt.Color(0, 102, 102));
        btn_edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
        });
        btn_edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit2.png"))); // NOI18N
        jLabel4.setText("Edit");
        btn_edit.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 190, 70));

        btn_course_list.setBackground(new java.awt.Color(0, 102, 102));
        btn_course_list.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btn_course_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_course_listMouseClicked(evt);
            }
        });
        btn_course_list.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/list_1.png"))); // NOI18N
        jLabel5.setText("Course List");
        btn_course_list.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 190, 70));

        btn_view_all_record.setBackground(new java.awt.Color(0, 102, 102));
        btn_view_all_record.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btn_view_all_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_view_all_recordMouseClicked(evt);
            }
        });
        btn_view_all_record.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view all record.png"))); // NOI18N
        jLabel6.setText("View All Record");
        btn_view_all_record.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 210, 70));

        btn_back.setBackground(new java.awt.Color(0, 102, 102));
        btn_back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        btn_back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/left-arrow.png"))); // NOI18N
        jLabel7.setText("Back");
        btn_back.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 190, 70));

        btn_logout.setBackground(new java.awt.Color(0, 102, 102));
        btn_logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        btn_logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jLabel8.setText("Logout");
        btn_logout.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 190, 70));

        btn_print.setBackground(new java.awt.Color(0, 102, 102));
        btn_print.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btn_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_printMouseClicked(evt);
            }
        });
        btn_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/printer-.png"))); // NOI18N
        jLabel9.setText("Print");
        btn_print.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 190, 70));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_view_all_record, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_course_list, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search_record, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btn_search_record, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btn_course_list, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btn_view_all_record, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 820));

        jPanel11.setBackground(new java.awt.Color(0, 153, 153));

        table_print.setBackground(new java.awt.Color(255, 255, 255));
        table_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Student name:");
        table_print.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 120, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Reclept no : SOC-");
        table_print.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 160, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Mode of Payment :");
        table_print.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 163, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Total in words :");
        table_print.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 125, 39));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("The following payment i the college office for the year :");
        table_print.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 399, 28));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Remark :");
        table_print.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 138, 40));
        table_print.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 839, 9));
        table_print.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 839, 10));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Date :");
        table_print.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 51, -1));

        txt_GSTIN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_GSTIN.setText("27AAATLO123");
        table_print.add(txt_GSTIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 163, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Roll No :");
        table_print.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 85, 22));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Sr.No");
        table_print.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 67, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Amount (Rs)");
        table_print.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 104, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("SGST 9%");
        table_print.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 95, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("to");
        table_print.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 30, 30));
        table_print.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 600, 210, 10));
        table_print.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 660, 210, 10));

        jlb_bankname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlb_bankname.setText("Bank  name :");
        table_print.add(jlb_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 90, -1));

        jlb_cheque_no.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlb_cheque_no.setText("Cheque no:");
        table_print.add(jlb_cheque_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jlb_ddo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlb_ddo.setText("DD no:");
        table_print.add(jlb_ddo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 60, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("GSTIN: ");
        table_print.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 60, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("CGST  9%");
        table_print.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 95, 30));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setText("Heads");
        table_print.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 95, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Course :");
        table_print.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 110, 40));

        txt_payment_mode.setText("No");
        table_print.add(txt_payment_mode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 210, 20));

        txt_cheque_no.setText("No");
        table_print.add(txt_cheque_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 210, 20));

        txt_ddno.setText("No");
        table_print.add(txt_ddno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 210, 20));

        txt_bank_name.setText("No");
        table_print.add(txt_bank_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 210, 20));

        txt_reclept.setText("No");
        table_print.add(txt_reclept, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 210, 20));

        txt_year2.setText("No");
        table_print.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 70, 30));

        txt_year1.setText("No");
        table_print.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 50, 30));

        txt_student_name.setText("No");
        table_print.add(txt_student_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 210, 20));

        txt_course.setText("a");
        table_print.add(txt_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 190, 20));

        txt_date.setText("No");
        table_print.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 210, 20));
        table_print.add(txt_reclept9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 210, 20));

        txt_roll_no.setText("No");
        table_print.add(txt_roll_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 120, 20));

        txt_total_amount.setText("No");
        table_print.add(txt_total_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 620, 210, 20));

        txt_cgst.setText("No");
        table_print.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 210, 20));

        txt_amount.setText("No");
        table_print.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 210, 20));

        txt_remark.setText("No");
        table_print.add(txt_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 280, 20));

        txt_sgst.setText("No");
        table_print.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 570, 210, 20));

        txt_total_in_words.setText("No");
        table_print.add(txt_total_in_words, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 280, 20));
        table_print.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 860, 20));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CNHN.jpg"))); // NOI18N
        table_print.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 200, 140));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel26.setText(" Hanoi Industrial University");
        table_print.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 500, 70));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Print Reclept");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(table_print, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(table_print, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 900, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
// TODO add your handling code here:
		update_fess_details update_fess = null;
		try {
			update_fess = new update_fess_details();
		} catch (Exception ex) {
			Logger.getLogger(Print_reciept.class.getName()).log(Level.SEVERE, null, ex);
		}
		update_fess.setVisible(true);
		this.dispose();
        }//GEN-LAST:event_btn_editMouseClicked

        private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
		// TODO add your handling code here:
		home home = new home();
		home.show();
		this.dispose();
        }//GEN-LAST:event_btn_homeMouseClicked

        private void btn_search_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_recordMouseClicked
		// TODO add your handling code here:
		search_record search = new search_record();
		search.show();
		this.dispose();
        }//GEN-LAST:event_btn_search_recordMouseClicked

        private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
		// TODO add your handling code here:
		System.exit(0);
        }//GEN-LAST:event_btn_backMouseClicked

        private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
		// TODO add your handling code here:
		Login_page login = new Login_page();
		login.show();
		this.dispose();
        }//GEN-LAST:event_btn_logoutMouseClicked

        private void btn_view_all_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_all_recordMouseClicked
		// TODO add your handling code here:
		View_ALL_record view = null;
		try {
			view = new View_ALL_record();
		} catch (Exception ex) {
			Logger.getLogger(Add_Fess.class.getName()).log(Level.SEVERE, null, ex);
		}
		view.show();
		this.dispose();

        }//GEN-LAST:event_btn_view_all_recordMouseClicked

        private void btn_course_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_course_listMouseClicked
		// TODO add your handling code here:
		edit_sourse edit = new edit_sourse();
		edit.show();
		this.dispose();
        }//GEN-LAST:event_btn_course_listMouseClicked

        private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
		search_record search = new search_record();
		search.show();
		this.dispose();
		// TODO add your handling code here:
        }//GEN-LAST:event_jLabel3MouseClicked

        private void btn_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseClicked
		// TODO add your handling code here:
		PrinterJob job = PrinterJob.getPrinterJob();
		job.setJobName("Print Data");

		job.setPrintable(new Printable() {
			public int print(Graphics pg, PageFormat pf, int pageNum) {
				pf.setOrientation(PageFormat.LANDSCAPE);
				if (pageNum > 0) {
					return Printable.NO_SUCH_PAGE;
				}

				Graphics2D g2 = (Graphics2D) pg;
				g2.translate(pf.getImageableX(), pf.getImageableY());
				g2.scale(0.47, 0.47);

				table_print.print(g2);

				return Printable.PAGE_EXISTS;

			}
		});
		boolean ok = job.printDialog();
		if (ok) {
			try {

				job.print();
			} catch (PrinterException ex) {
				ex.printStackTrace();
			}
		}
        }//GEN-LAST:event_btn_printMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Print_reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Print_reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Print_reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Print_reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Print_reciept().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_back;
    private javax.swing.JPanel btn_course_list;
    private javax.swing.JPanel btn_edit;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_logout;
    private javax.swing.JPanel btn_print;
    private javax.swing.JPanel btn_search_record;
    private javax.swing.JPanel btn_view_all_record;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel jlb_bankname;
    private javax.swing.JLabel jlb_cheque_no;
    private javax.swing.JLabel jlb_ddo;
    private javax.swing.JPanel table_print;
    private javax.swing.JLabel txt_GSTIN;
    private javax.swing.JLabel txt_amount;
    private javax.swing.JLabel txt_bank_name;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_cheque_no;
    private javax.swing.JLabel txt_course;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_ddno;
    private javax.swing.JLabel txt_payment_mode;
    private javax.swing.JLabel txt_reclept;
    private javax.swing.JLabel txt_reclept9;
    private javax.swing.JLabel txt_remark;
    private javax.swing.JLabel txt_roll_no;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_student_name;
    private javax.swing.JLabel txt_total_amount;
    private javax.swing.JLabel txt_total_in_words;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
